sudo: required
language: node_js
services:
  - mysql
cache:
  directories:
    - node_modules
node_js:
  - "10"
notifications:
  email:
    - ahmed.abdelhay.90@gmail.com
before_install:
  - npm ci
  - mysql -e 'CREATE DATABASE database_test'
script:
  - npm test
