sudo: required
language: node_js
services:
  - docker
cache:
  directories:
    - node_modules
node_js:
  - "10"
notifications:
  email:
    - ahmed.abdelhay.90@gmail.com
before_install:
  - docker build -t fullstack-challenge .
script:
  - npm test
