version: '3'

services:
    nginx:
        build:
            context: ./ci/nginx
            dockerfile: Dockerfile
            restart: always
            ports:
                - 80:80
            depends_on:
                - api-server
    webapp:
        build:
            context: ./client
            dockerfile: Dockerfile
        container_name: web
        ports:
            - 80:80
        environment:
            - NODE_ENV=production
        depends_on:
            - api-server
    api-server:
        build:
            dockerfile: Dockerfile
            context: .
        container_name: api
        ports:
            - 8080:8080
        environment:
            - NODE_ENV=production
        command: npm start
        depends_on:
            - mysql
    mysql:
        image: mysql
        container_name: api_db
        environment:
            - MYSQL_DATABASE=database_production
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=root
        command: --character-set-server=utf8
        restart: always
        ports:
            - 3306:3306
        volumes:
            - db:/var/lib/mysql

volumes:
    db:
